ingest:
    - source: 'web'
      source_path: 'https://mongodb-partners.github.io/maap-chatbot-builder/docs/intro'
      chunk_size: 1000
      chunk_overlap: 100
    
embedding:
    class_name: Azure-OpenAI-Embeddings
    model_name: 'text-embedding-ada-002' 
    deployment_name: "leafy-embedding-ada-002"
    api_version: "2023-03-15-preview"
    azure_openai_api_instance_name: "leafyhospopenai"

vector_store:
    connectionString: 'mongodb+srv://admin:test123@demo.fmxyq.mongodb.net/'
    dbName: 'chatter'
    collectionName: 'embedded_content'
    embeddingKey: 'embedding'
    textKey: 'text'
    vectorSearchIndexName: 'vector_index'
    numCandidates: 150
    minScore: 0.1 
    similarityFunction: 'cosine'
llms:
    class_name: AzureOpenAI
    deployment_name: "leafyhosp-gpt-35-turbo"
    api_version: "2023-03-15-preview"
    azure_openai_api_instance_name: "leafyhospopenai"
    temprature: ''